name: Testnet Harvest

env:
  CI: true
  FORCE_COLOR: true

on:
  #schedule:
  #  - cron: "*/15 * * * *"

  push:
    branches: [main]
    paths:
      - ".github/workflows/testnet-harvest.yml"
      - "LUSDChickenBonds/bindings/scripts/harvest.ts"

  pull_request:
    paths:
      - ".github/workflows/testnet-harvest.yml"
      - "LUSDChickenBonds/bindings/scripts/harvest.ts"

jobs:
  harvest:
    name: Call harvest on testnet
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Compile contracts
        working-directory: LUSDChickenBonds
        run: forge build

      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
        env:
          # Workaround for https://github.com/actions/setup-node/issues/317
          FORCE_COLOR: 0

      - name: Install dependencies & generate typings
        working-directory: LUSDChickenBonds/bindings
        run: yarn install --frozen-lockfile

      - name: Send harvest transaction
        working-directory: LUSDChickenBonds/bindings
        run: yarn ts-node scripts/harvest.ts
        env:
          RPC_URL: ${{ secrets.HARVESTER_RPC_URL }}
          PRIVATE_KEY: ${{ secrets.HARVESTER_PRIVATE_KEY }}
